#########################################################################################################################################
---
- hosts: localhost
  gather_facts: false
  name: NetApp snapshot Creation
  vars:
    login: &login
     hostname: "{{ prod_cluster_IP }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     https: "{{ https_option }}"
     validate_certs: "{{ validate_certs_option }}"
  vars_files:
  - variables.yml
  tasks:
      - name: "Reading snapshot information"
        read_csv:
          path: snapshot_sheet.csv
        register: snapshot_sheet

      - name: snapshot creation for volumes
        tags:
          - create
        na_ontap_snapshot:
          state: present
          snapshot: "{{item.name}}"
          volume: "{{item.volume}}" 
          comment:  "ansible created snapshot"
          vserver: "{{item.vserver}}" 
          <<: *login
        loop: "{{ snapshot_sheet.list }}"
        loop_control:
          loop_var: item

          
      - debug: msg="The snapshots have been created"

