#########################################################################################################################################
---
- hosts: localhost
  gather_facts: false
  name: NetApp volume Creation
  vars:
    login: &login
     hostname: "{{ prod_cluster_IP }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     https: "{{ https_option }}"
     validate_certs: "{{ validate_certs_option }}"
  vars_files:
  - variables.yml
  tasks:
      - name: "Reading Export Policy information"
        read_csv:
          path: export_policy_sheet.csv
        register: export_policy_sheet

      - name: export policy and rule creation
        na_ontap_export_policy_rule:
          state: present
          allow_suid: true
          client_match: "{{ item.client_match }}"
          policy_name: "{{ item.name }}"
          protocol: "any"
          ro_rule: "any"
          rw_rule: "any"
          super_user_security: "any"
          vserver: "{{ item.vserver }}"
          <<: *login
        loop: "{{ export_policy_sheet.list }}"
        loop_control:
          loop_var: item

      - debug: msg="The export policy and rules  have been created"
